### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by aaronjs99** [Ayush1651999/GNR652#1]
All three Jupyter Notebook files are not being rendered on GitHub. I checked with Jupyter Notebooks from other repositories but they seem to be working. Probably it is something wrong with the code.
Please look into the code. I'll check it out myself as well.

**Comment by Ayush1651999** [comment]
Actually its for storing the codes, the reason they aren't working is because the data isn't there. I will complete the repo with data in some days. Thanks for pointing it out

**Comment by aaronjs99** [comment]
Cool
